name: next_previous_element
version: 0.10.0+3
author: Jim Heyne <jheyne@gmail.com>
homepage: https://github.com/jheyne/next_previous_element
description: Dart Polymer component with previous/next buttons for a presentation area. Akin to a slideshow. The presentation area can hold any content.
dependencies:
  core_elements: any
  polymer: any
  unittest: any
transformers:
- polymer:
    entry_points:
    - example/app.html
