name: next_previous_element
version: 0.10.1
author: Jim Heyne <jheyne@gmail.com>
homepage: https://github.com/jheyne/next_previous_element
description: Dart Polymer component with previous/next buttons for a presentation area. Akin to a slideshow. The presentation area can hold any content.
dependencies:
  core_elements: ">=0.3.1+1 <0.5.0"
  polymer: ">=0.15.0+1 <0.17.0"
  unittest: ">=0.11.0+5 <0.13.0"
transformers:
- polymer:
    entry_points:
    - example/app.html
